import type { TelemetryPoint } from './telemetry.types';
const timestamp = '2026-07-15T00:00:00.000Z';
const point = (
  input: Omit<TelemetryPoint, 'version' | 'createdAt' | 'updatedAt'>,
): TelemetryPoint => ({ ...input, version: 1, createdAt: timestamp, updatedAt: timestamp });
export const telemetryPointSeed: TelemetryPoint[] = [
  point({
    id: 'gds-101',
    code: 'GDS-101',
    source: 'GDS',
    name: '泵区东侧探测器',
    areaId: 'area-02',
    areaName: '催化裂化装置',
    equipmentName: 'P-201A 原料泵',
    metricKey: 'gasConcentration',
    unit: '%LEL',
    configuration: { gasType: '可燃气体', alarmLevel1: 25, alarmLevel2: 40 },
    currentMetrics: { gasConcentration: 18 },
    status: 'normal',
    onlineStatus: 'online',
    lastSampleAt: timestamp,
  }),
  point({
    id: 'gds-102',
    code: 'GDS-102',
    source: 'GDS',
    name: '压缩机区探测器',
    areaId: 'area-02',
    areaName: '催化裂化装置',
    equipmentName: 'C-201 压缩机',
    metricKey: 'gasConcentration',
    unit: 'ppm',
    configuration: { gasType: '硫化氢', alarmLevel1: 10, alarmLevel2: 20 },
    currentMetrics: { gasConcentration: 3 },
    status: 'normal',
    onlineStatus: 'online',
    lastSampleAt: timestamp,
  }),
  point({
    id: 'voc-001',
    code: 'VOC-001',
    source: 'VOC',
    name: 'RTO 出口',
    areaId: 'area-04',
    areaName: '硫磺回收装置',
    equipmentName: 'RTO-01',
    metricKey: 'concentration',
    unit: 'mg/m³',
    configuration: { pointType: '有组织排口', pollutantType: '非甲烷总烃', limitValue: 60 },
    currentMetrics: { concentration: 56, flow: 12000 },
    status: 'warning',
    onlineStatus: 'online',
    lastSampleAt: timestamp,
  }),
  point({
    id: 'voc-002',
    code: 'VOC-002',
    source: 'VOC',
    name: '东厂界监测点',
    areaId: 'area-05',
    areaName: '厂界',
    equipmentName: '厂界站东',
    metricKey: 'concentration',
    unit: 'mg/m³',
    configuration: { pointType: '厂界监测点', pollutantType: '苯系物', limitValue: 4 },
    currentMetrics: { concentration: 1.2, flow: 0 },
    status: 'normal',
    onlineStatus: 'online',
    lastSampleAt: timestamp,
  }),
  point({
    id: 'mes-pt-101',
    code: 'PT-101',
    source: 'MES',
    name: '进料泵出口压力',
    areaId: 'area-01',
    areaName: '常减压装置',
    equipmentName: 'P-101 进料泵',
    metricKey: 'value',
    unit: 'MPa',
    configuration: { processStep: '进料', parameterType: '压力', lowerLimit: 0.5, upperLimit: 1.2 },
    currentMetrics: { value: 0.82 },
    status: 'normal',
    onlineStatus: 'online',
    lastSampleAt: timestamp,
  }),
  point({
    id: 'mes-tt-201',
    code: 'TT-201',
    source: 'MES',
    name: '加热炉出口温度',
    areaId: 'area-01',
    areaName: '常减压装置',
    equipmentName: 'F-201 加热炉',
    metricKey: 'value',
    unit: '℃',
    configuration: { processStep: '加热', parameterType: '温度', lowerLimit: 330, upperLimit: 370 },
    currentMetrics: { value: 352 },
    status: 'normal',
    onlineStatus: 'online',
    lastSampleAt: timestamp,
  }),
];
