import type { EmergencyPlan, EmergencyPlanConfig } from './emergency-plan.types';
const timestamp = '2026-07-15T00:00:00.000Z';
const configs: Array<{ id: string; code: string; version: string; config: EmergencyPlanConfig }> = [
  {
    id: 'tpl-001',
    code: 'QHSE-FCC-LEAK-01',
    version: 'V3.2',
    config: {
      name: '可燃气体泄漏现场处置方案',
      category: '现场处置方案',
      eventType: '可燃气体泄漏',
      applicableArea: '催化裂化装置',
      medium: '烃类可燃气体',
      responseLevel: 'II级',
      triggerRule: 'GDS 达到二级报警或多点浓度持续上升',
      notificationTargets: ['岗位人员', '装置负责人', '生产调度', '消防气防'],
      steps: ['停止作业并撤离现场', '切断物料与火源', '设置警戒并持续监测'],
      resources: ['泡沫消防车', '空气呼吸器', '防爆堵漏工具'],
      effectiveDate: '2026-05-01',
      expiryDate: '2026-08-15',
      ownerDepartment: '催化裂化装置',
    },
  },
  {
    id: 'tpl-002',
    code: 'QHSE-GAS-H2S-02',
    version: 'V2.6',
    config: {
      name: '硫化氢泄漏专项应急预案',
      category: '专项应急预案',
      eventType: '有毒气体泄漏',
      applicableArea: '全厂含硫装置',
      medium: '硫化氢',
      responseLevel: 'I级',
      triggerRule: 'H₂S 浓度达到 20ppm 或出现人员中毒',
      notificationTargets: ['应急指挥人员', '消防气防', '医疗救护'],
      steps: ['佩戴正压式呼吸器', '上风向组织撤离', '搜救受影响人员'],
      resources: ['气防车', '空气呼吸器', '急救担架'],
      effectiveDate: '2026-03-15',
      expiryDate: '2027-03-14',
      ownerDepartment: '安全环保部',
    },
  },
  {
    id: 'tpl-003',
    code: 'QHSE-ENV-VOC-03',
    version: 'V2.1',
    config: {
      name: 'VOC 异常排放专项处置预案',
      category: '专项应急预案',
      eventType: '环境污染事件',
      applicableArea: 'VOC 治理设施及排口',
      medium: '非甲烷总烃',
      responseLevel: 'III级',
      triggerRule: '排口连续 10 分钟超限或治理效率低于 80%',
      notificationTargets: ['环保管理人员', '装置负责人', '生产调度'],
      steps: ['核查在线数据与设备状态', '切换备用治理设施', '降低相关装置负荷'],
      resources: ['便携式 VOC 分析仪', '移动治理设备'],
      effectiveDate: '2026-04-20',
      expiryDate: '2027-04-19',
      ownerDepartment: '安全环保部',
    },
  },
];
export const emergencyPlanSeed: EmergencyPlan[] = configs.map(({ id, code, version, config }) => ({
  id,
  code,
  ...config,
  version,
  status: '生效中',
  publishStatus: '已发布',
  versions: [
    { ...config, version, publishedAt: timestamp, publisher: '赵磊', publisherId: 'user-qhse' },
  ],
  drills: [],
  revision: 1,
  createdAt: timestamp,
  updatedAt: timestamp,
}));
