import type { Hazard, HazardAction, HazardStatus } from './hazard.types';

const createdAt = '2026-07-14T00:00:00.000Z';

const rows: Array<
  Omit<
    Hazard,
    'overdue' | 'supervised' | 'evidence' | 'operations' | 'version' | 'createdAt' | 'updatedAt'
  >
> = [
  {
    id: 'hazard-001',
    code: 'YH20260711001',
    title: 'P-208 同类高温泵法兰垫片选型待复核',
    areaId: 'area-02',
    areaName: '催化裂化装置',
    level: '重大',
    source: '复盘整改',
    category: '设备完整性',
    ownerDepartment: '设备管理部',
    owner: '孙工',
    discoveredAt: '2026-07-11',
    deadline: '2026-07-15',
    status: '整改中',
    riskUnitId: 'risk-001',
    recurrenceCount: 1,
    description: '事件复盘发现同类高温泵可能存在垫片选型裕量不足。',
    measures: ['完成 12 台同类泵材料复核', '不符合项停机窗口更换'],
  },
  {
    id: 'hazard-002',
    code: 'YH20260710006',
    title: '储罐区东侧消防通道临时占用',
    areaId: 'area-05',
    areaName: '储罐区',
    level: '较大',
    source: '现场检查',
    category: '消防安全',
    ownerDepartment: '储运部',
    owner: '何军',
    discoveredAt: '2026-07-10',
    deadline: '2026-07-12',
    status: '待验收',
    riskUnitId: 'risk-002',
    recurrenceCount: 0,
    description: '施工材料占用部分消防通道，现场已完成清运并提交验收。',
    measures: ['清除占道物料', '恢复消防通道标识'],
  },
  {
    id: 'hazard-003',
    code: 'YH20260712003',
    title: 'RTO 旁路阀铅封台账记录不完整',
    areaId: 'area-04',
    areaName: '硫磺回收装置',
    level: '一般',
    source: '专项检查',
    category: '环保设施',
    ownerDepartment: '安全环保部',
    owner: '周敏',
    discoveredAt: '2026-07-12',
    deadline: '2026-07-16',
    status: '待整改',
    riskUnitId: 'risk-004',
    recurrenceCount: 0,
    description: '现场铅封编号与月度台账存在一处缺项。',
    measures: ['补齐铅封编号', '复核当月巡检记录'],
  },
  {
    id: 'hazard-004',
    code: 'YH20260709009',
    title: 'F-201 炉前压力表校验标签模糊',
    areaId: 'area-01',
    areaName: '常减压装置',
    level: '一般',
    source: '现场检查',
    category: '仪表管理',
    ownerDepartment: '仪控中心',
    owner: '刘工',
    discoveredAt: '2026-07-09',
    deadline: '2026-07-11',
    status: '已关闭',
    riskUnitId: 'risk-003',
    recurrenceCount: 0,
    description: '校验标签字迹模糊，已重新张贴并完成照片取证。',
    measures: ['更换校验标签'],
  },
  {
    id: 'hazard-005',
    code: 'YH20260713002',
    title: '装车栈台一处静电接地夹磨损',
    areaId: 'area-06',
    areaName: '油品装卸区',
    level: '较大',
    source: '现场检查',
    category: '电气安全',
    ownerDepartment: '储运部',
    owner: '宋伟',
    discoveredAt: '2026-07-13',
    deadline: '2026-07-13',
    status: '待整改',
    riskUnitId: 'risk-006',
    recurrenceCount: 1,
    description: '接地夹齿口磨损，夹持可靠性下降。',
    measures: ['立即停用对应车位', '更换防爆静电接地夹'],
  },
  {
    id: 'hazard-006',
    code: 'YH20260713005',
    title: 'GDS 趋势预警转化现场排查',
    areaId: 'area-02',
    areaName: '催化裂化装置',
    level: '较大',
    source: '预警转化',
    category: '泄漏管理',
    ownerDepartment: '催化裂化装置',
    owner: '李建国',
    discoveredAt: '2026-07-13',
    deadline: '2026-07-13',
    status: '整改中',
    riskUnitId: 'risk-001',
    recurrenceCount: 0,
    description: 'GDS-101 浓度持续上升，已转化隐患并开展泄漏点排查。',
    measures: ['便携仪器复测', '检查泵密封及法兰'],
  },
];

const actionByStatus: Record<HazardStatus, HazardAction> = {
  待整改: '上报',
  整改中: '开始整改',
  待验收: '提交验收',
  已关闭: '验收关闭',
};

export const hazardSeed: Hazard[] = rows.map((row) => ({
  ...row,
  overdue: row.status !== '已关闭' && row.deadline < '2026-07-15',
  supervised: row.level === '重大',
  acceptanceOpinion: row.status === '已关闭' ? '整改证据完整，验收合格' : undefined,
  evidence: ['待验收', '已关闭'].includes(row.status)
    ? [
        {
          id: `${row.id}-evidence-1`,
          name: '现场整改完成照片.jpg',
          category: '整改完成',
          uploaderId: 'user-qhse',
          uploader: '赵磊',
          uploadedAt: createdAt,
          note: '现场复核材料',
        },
      ]
    : [],
  operations: [
    {
      id: `${row.id}-operation-1`,
      action: actionByStatus[row.status],
      operatorId: 'user-qhse',
      operator: '赵磊',
      operatedAt: createdAt,
      detail: `初始化隐患状态：${row.status}`,
    },
  ],
  version: 1,
  createdAt,
  updatedAt: createdAt,
}));
