import type { CommunicationDispatch } from './communication.types';
const timestamp = '2026-07-15T00:00:00.000Z';
export const communicationSeed: CommunicationDispatch[] = [
  {
    id: 'communication-001',
    eventId: 'evt-001',
    eventCode: 'W20260711001',
    eventTitle: '可燃气体浓度持续上升',
    areaName: '催化裂化装置',
    eventLevel: 'high',
    status: '待确认',
    escalationLevel: 0,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    tasks: [
      {
        id: 'comm-001',
        eventId: 'evt-001',
        eventTitle: '可燃气体浓度持续上升',
        receiver: '王强',
        receiverRole: '岗位操作员',
        channel: 'App消息',
        sendTime: '2026-07-15T08:28:45.000Z',
        deliveryStatus: '已送达',
        confirmStatus: '未确认',
        retryCount: 0,
        escalationLevel: 0,
      },
    ],
  },
  {
    id: 'communication-002',
    eventId: 'evt-002',
    eventCode: 'W20260711002',
    eventTitle: 'RTO 出口浓度接近限值',
    areaName: '硫磺回收装置',
    eventLevel: 'medium',
    status: '已确认',
    escalationLevel: 0,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    tasks: [
      {
        id: 'comm-002',
        eventId: 'evt-002',
        eventTitle: 'RTO 出口浓度接近限值',
        receiver: '周敏',
        receiverRole: '环保管理人员',
        channel: 'App消息',
        sendTime: '2026-07-15T08:19:10.000Z',
        deliveryStatus: '已送达',
        confirmStatus: '已确认',
        confirmTime: '2026-07-15T08:19:42.000Z',
        confirmedBy: '周敏',
        retryCount: 0,
        escalationLevel: 0,
      },
    ],
  },
  {
    id: 'communication-003',
    eventId: 'evt-003',
    eventCode: 'W20260711003',
    eventTitle: '泵出口压力偏高',
    areaName: '常减压装置',
    eventLevel: 'low',
    status: '已确认',
    escalationLevel: 0,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    tasks: [
      {
        id: 'comm-003',
        eventId: 'evt-003',
        eventTitle: '泵出口压力偏高',
        receiver: '陈涛',
        receiverRole: '生产调度',
        channel: '短信',
        sendTime: '2026-07-15T08:11:40.000Z',
        deliveryStatus: '已送达',
        confirmStatus: '已确认',
        confirmTime: '2026-07-15T08:12:08.000Z',
        confirmedBy: '陈涛',
        retryCount: 0,
        escalationLevel: 0,
      },
    ],
  },
];
