import type { EmergencyEvent } from './emergency-event.types';

const createdAt = '2026-07-11T00:00:00.000Z';

export const emergencyEventSeed: EmergencyEvent[] = [
  {
    id: 'lifecycle-001',
    eventId: 'evt-001',
    code: 'EC20260711001',
    title: '可燃气体浓度持续上升',
    areaId: 'area-02',
    areaName: '催化裂化装置',
    source: 'GDS',
    status: '响应中',
    responseLevel: 'II级',
    commander: '陈涛 / 生产调度',
    ownerDepartment: '催化裂化装置',
    startedAt: '2026-07-11T08:28:42.000Z',
    updatedAt: '2026-07-11T08:30:18.000Z',
    createdAt,
    summary: 'FCC 泵区 GDS-101 达到二级报警，已启动泄漏现场处置方案。',
    version: 1,
    evidence: [],
    operations: [
      {
        id: 'lifecycle-001-1',
        action: '事件生成',
        operatorId: 'system',
        operator: '系统',
        operatedAt: '2026-07-11T08:28:42.000Z',
        toStatus: '待研判',
        toLevel: 'II级',
        detail: 'GDS 二级报警自动生成应急事件。',
      },
      {
        id: 'lifecycle-001-2',
        action: '告警确认',
        operatorId: 'user-operator',
        operator: '王强',
        operatedAt: '2026-07-11T08:29:03.000Z',
        fromStatus: '待研判',
        toStatus: '待研判',
        fromLevel: 'II级',
        toLevel: 'II级',
        detail: '现场确认存在异常气味和可燃气体浓度升高。',
      },
      {
        id: 'lifecycle-001-3',
        action: '研判启动',
        operatorId: 'user-dispatcher',
        operator: '陈涛',
        operatedAt: '2026-07-11T08:30:18.000Z',
        fromStatus: '待研判',
        toStatus: '响应中',
        fromLevel: 'II级',
        toLevel: 'II级',
        detail: '研判确认事件需要应急响应，已启动现场处置。',
      },
    ],
  },
  {
    id: 'lifecycle-002',
    eventId: 'evt-002',
    code: 'EC20260711002',
    title: 'RTO 出口浓度接近限值',
    areaId: 'area-04',
    areaName: '硫磺回收装置',
    source: 'VOC',
    status: '监控中',
    responseLevel: 'IV级',
    commander: '周敏 / 环保管理',
    ownerDepartment: '安全环保部',
    startedAt: '2026-07-11T08:19:06.000Z',
    updatedAt: '2026-07-11T09:05:21.000Z',
    createdAt,
    summary: '治理设施参数已恢复，排口浓度连续 30 分钟低于预警值，进入持续监控。',
    version: 1,
    evidence: [],
    operations: [
      {
        id: 'lifecycle-002-1',
        action: '事件生成',
        operatorId: 'system',
        operator: '系统',
        operatedAt: '2026-07-11T08:19:06.000Z',
        toStatus: '待研判',
        toLevel: 'IV级',
        detail: 'VOC 趋势预警生成应急事件。',
      },
      {
        id: 'lifecycle-002-2',
        action: '研判启动',
        operatorId: 'user-environment',
        operator: '周敏',
        operatedAt: '2026-07-11T08:21:12.000Z',
        fromStatus: '待研判',
        toStatus: '响应中',
        fromLevel: 'IV级',
        toLevel: 'IV级',
        detail: '启动环保异常现场核查。',
      },
      {
        id: 'lifecycle-002-3',
        action: '终止响应',
        operatorId: 'user-environment',
        operator: '周敏',
        operatedAt: '2026-07-11T09:05:21.000Z',
        fromStatus: '响应中',
        toStatus: '监控中',
        fromLevel: 'IV级',
        toLevel: 'IV级',
        detail: '治理设施恢复稳定，终止响应并持续监控。',
      },
    ],
  },
  {
    id: 'lifecycle-003',
    eventId: 'evt-003',
    code: 'EC20260711003',
    title: '泵出口压力偏高',
    areaId: 'area-01',
    areaName: '常减压装置',
    source: 'MES',
    status: '监控中',
    responseLevel: 'IV级',
    commander: '高峰 / 装置值班',
    ownerDepartment: '常减压装置',
    startedAt: '2026-07-11T08:11:37.000Z',
    updatedAt: '2026-07-11T09:46:30.000Z',
    createdAt,
    summary: '压力波动原因已排查，现场数据稳定，等待提交关闭审批。',
    version: 1,
    evidence: [
      {
        id: 'lifecycle-003-e1',
        name: 'P-102 出口压力稳定性趋势',
        category: '监测报告',
        uploaderId: 'user-unit-manager',
        uploader: '高峰',
        uploadedAt: '2026-07-11T10:12:30.000Z',
        note: '连续 30 分钟压力处于正常区间。',
        hash: 'META-EC0301',
      },
    ],
    operations: [
      {
        id: 'lifecycle-003-1',
        action: '事件生成',
        operatorId: 'system',
        operator: '系统',
        operatedAt: '2026-07-11T08:11:37.000Z',
        toStatus: '待研判',
        toLevel: 'IV级',
        detail: 'MES 压力异常生成应急事件。',
      },
      {
        id: 'lifecycle-003-2',
        action: '研判启动',
        operatorId: 'user-unit-manager',
        operator: '高峰',
        operatedAt: '2026-07-11T08:15:06.000Z',
        fromStatus: '待研判',
        toStatus: '响应中',
        fromLevel: 'IV级',
        toLevel: 'IV级',
        detail: '启动设备和工艺联合排查。',
      },
      {
        id: 'lifecycle-003-3',
        action: '终止响应',
        operatorId: 'user-unit-manager',
        operator: '高峰',
        operatedAt: '2026-07-11T09:46:30.000Z',
        fromStatus: '响应中',
        toStatus: '监控中',
        fromLevel: 'IV级',
        toLevel: 'IV级',
        detail: '压力恢复正常，进入稳定性监控。',
      },
    ],
  },
  {
    id: 'lifecycle-004',
    eventId: 'evt-004',
    code: 'EC20260713004',
    title: '装卸区可燃气体趋势异常',
    areaId: 'area-06',
    areaName: '油品装卸区',
    source: 'GDS',
    status: '待研判',
    responseLevel: 'IV级',
    commander: '待指定',
    ownerDepartment: '储运部',
    startedAt: '2026-07-13T07:42:10.000Z',
    updatedAt: '2026-07-13T07:42:10.000Z',
    createdAt,
    summary: 'GDS-LOAD-06 连续五个采样点上升，等待现场研判。',
    version: 1,
    evidence: [],
    operations: [
      {
        id: 'lifecycle-004-1',
        action: '事件生成',
        operatorId: 'system',
        operator: '系统',
        operatedAt: '2026-07-13T07:42:10.000Z',
        toStatus: '待研判',
        toLevel: 'IV级',
        detail: '趋势规则命中，自动生成待研判事件。',
      },
    ],
  },
];
