import type { EmergencyResource } from './emergency-resource.types';
const timestamp = '2026-07-15T00:00:00.000Z';
export const emergencyResourceSeed: EmergencyResource[] = [
  {
    id: 'res-001',
    code: 'FIRE-TRUCK-01',
    name: '泡沫消防车',
    type: '消防',
    quantity: '2 辆',
    totalQuantity: 2,
    availableQuantity: 2,
    unit: '辆',
    location: '消防站',
    eta: '3 分钟',
    status: '待命',
    owner: '张伟',
    contact: '6001',
    lastInspection: '2026-07-01',
    nextInspection: '2026-08-01',
    inspectionStatus: '检查合格',
    batches: [
      {
        id: 'batch-001',
        batchNo: 'FIRE-202607',
        quantity: 2,
        availableQuantity: 2,
        receivedAt: '2026-07-01',
        expiryDate: '2030-12-31',
      },
    ],
    dispatches: [],
    inspectionRecords: [],
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'res-002',
    code: 'SCBA-FCC-01',
    name: '正压式空气呼吸器',
    type: '气防',
    quantity: '12 套',
    totalQuantity: 12,
    availableQuantity: 12,
    unit: '套',
    location: 'FCC 气防柜',
    eta: '5 分钟',
    status: '待命',
    owner: '刘洋',
    contact: '6218',
    lastInspection: '2026-07-08',
    nextInspection: '2026-08-08',
    inspectionStatus: '检查合格',
    batches: [
      {
        id: 'batch-002-a',
        batchNo: 'SCBA-202501',
        quantity: 4,
        availableQuantity: 4,
        receivedAt: '2025-01-10',
        expiryDate: '2026-08-01',
      },
      {
        id: 'batch-002-b',
        batchNo: 'SCBA-202601',
        quantity: 8,
        availableQuantity: 8,
        receivedAt: '2026-01-10',
        expiryDate: '2028-01-10',
      },
    ],
    dispatches: [],
    inspectionRecords: [],
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'res-003',
    code: 'FIRE-ROBOT-01',
    name: '防爆消防机器人',
    type: '消防',
    quantity: '1 台',
    totalQuantity: 1,
    availableQuantity: 1,
    unit: '台',
    location: '消防站二库',
    eta: '8 分钟',
    status: '待命',
    owner: '张伟',
    contact: '6001',
    lastInspection: '2026-06-18',
    nextInspection: '2026-07-10',
    inspectionStatus: '需要维护',
    batches: [],
    dispatches: [],
    inspectionRecords: [],
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];
