import type { RiskUnit } from './risk.types';

const seededAt = new Date('2026-07-14T00:00:00.000Z');

export const riskSeed: RiskUnit[] = [
  {
    id: 'risk-001',
    code: 'RU-FCC-P208',
    name: 'P-208 高温油泵单元',
    parentName: '反应油气系统',
    areaId: 'area-02',
    areaName: '催化裂化装置',
    ownerDepartment: '催化裂化装置',
    owner: '李建国',
    medium: '高温油气、可燃气体',
    accidentTypes: ['泄漏', '火灾爆炸'],
    staticLevel: 'high',
    currentLevel: 'critical',
    controls: ['双端面机械密封与泄漏收集', '泵区 GDS 连续监测', '高温法兰每班巡检'],
    linkedGds: 4,
    linkedVoc: 0,
    linkedMes: 6,
    linkedPlans: 2,
    dynamicFactors: [
      { source: 'GDS', label: 'GDS-101 浓度持续上升', impact: 'up', status: '38% LEL' },
      { source: '作业许可', label: '泵出口法兰一级动火', impact: 'up', status: '作业中' },
    ],
    assessments: [],
    controlRecords: [],
    version: 1,
    updatedAt: seededAt,
  },
  {
    id: 'risk-002',
    code: 'RU-TANK-201',
    name: 'T-201 汽油储罐单元',
    parentName: '成品油罐组',
    areaId: 'area-05',
    areaName: '储罐区',
    ownerDepartment: '储运部',
    owner: '何军',
    medium: '汽油',
    accidentTypes: ['火灾爆炸', '中毒窒息'],
    staticLevel: 'high',
    currentLevel: 'high',
    controls: ['液位高高联锁', '罐区泡沫灭火系统', '防火堤完整性月检'],
    linkedGds: 6,
    linkedVoc: 2,
    linkedMes: 4,
    linkedPlans: 2,
    dynamicFactors: [
      { source: 'VOC', label: '储罐呼吸气排口负荷偏高', impact: 'watch', status: '44 mg/m³' },
    ],
    assessments: [],
    controlRecords: [],
    version: 1,
    updatedAt: seededAt,
  },
  {
    id: 'risk-003', code: 'RU-CDU-F201', name: 'F-201 加热炉单元', parentName: '常减压加热系统',
    areaId: 'area-01', areaName: '常减压装置', ownerDepartment: '常减压装置', owner: '高峰',
    medium: '燃料气、原油', accidentTypes: ['炉膛爆燃', '高温灼烫'], staticLevel: 'high', currentLevel: 'high',
    controls: ['燃烧器火焰检测', '炉膛压力联锁', '进料低流量切断'], linkedGds: 3, linkedVoc: 0, linkedMes: 8, linkedPlans: 1,
    dynamicFactors: [{ source: 'MES', label: '泵出口压力接近上限', impact: 'watch', status: '2.34 MPa' }],
    assessments: [], controlRecords: [], version: 1, updatedAt: seededAt,
  },
  {
    id: 'risk-004', code: 'RU-SRU-RTO', name: 'RTO 废气治理单元', parentName: '尾气治理系统',
    areaId: 'area-04', areaName: '硫磺回收装置', ownerDepartment: '安全环保部', owner: '周敏',
    medium: '含硫尾气、VOC', accidentTypes: ['异常排放', '设备火灾'], staticLevel: 'medium', currentLevel: 'medium',
    controls: ['燃烧室温度联锁', '进出口浓度在线监测', '旁路阀门铅封管理'], linkedGds: 2, linkedVoc: 3, linkedMes: 5, linkedPlans: 1,
    dynamicFactors: [{ source: 'VOC', label: 'RTO 出口浓度接近限值', impact: 'watch', status: '56 mg/m³' }],
    assessments: [], controlRecords: [], version: 1, updatedAt: seededAt,
  },
  {
    id: 'risk-005', code: 'RU-HCU-R101', name: 'R-101 加氢反应单元', parentName: '加氢反应系统',
    areaId: 'area-03', areaName: '加氢装置', ownerDepartment: '加氢装置', owner: '马勇', medium: '氢气、硫化氢',
    accidentTypes: ['火灾爆炸', '中毒'], staticLevel: 'critical', currentLevel: 'high',
    controls: ['反应器超温泄压', '循环氢纯度在线分析', '硫化氢区域报警'], linkedGds: 7, linkedVoc: 0, linkedMes: 9, linkedPlans: 2,
    dynamicFactors: [{ source: 'MES', label: '装置运行参数稳定', impact: 'watch', status: '稳定' }],
    assessments: [], controlRecords: [], version: 1, updatedAt: seededAt,
  },
  {
    id: 'risk-006', code: 'RU-LOAD-01', name: '汽车装车栈台单元', parentName: '油品装卸系统',
    areaId: 'area-06', areaName: '油品装卸区', ownerDepartment: '储运部', owner: '宋伟', medium: '汽柴油',
    accidentTypes: ['泄漏', '车辆伤害'], staticLevel: 'medium', currentLevel: 'medium',
    controls: ['静电接地联锁', '鹤管拉断阀', '车辆限速与导流'], linkedGds: 4, linkedVoc: 2, linkedMes: 2, linkedPlans: 1,
    dynamicFactors: [{ source: '作业许可', label: '装卸栈台临时用电', impact: 'watch', status: '待审批' }],
    assessments: [], controlRecords: [], version: 1, updatedAt: seededAt,
  },
];
