import type { RiskUnit } from './risk.types';

const seededAt = new Date('2026-07-14T00:00:00.000Z');

export const riskSeed: RiskUnit[] = [
  {
    id: 'risk-001',
    code: 'RU-FCC-P208',
    name: 'P-208 高温油泵单元',
    parentName: '反应油气系统',
    areaId: 'area-02',
    areaName: '催化裂化装置',
    ownerDepartment: '催化裂化装置',
    owner: '李建国',
    medium: '高温油气、可燃气体',
    accidentTypes: ['泄漏', '火灾爆炸'],
    staticLevel: 'high',
    currentLevel: 'critical',
    controls: ['双端面机械密封与泄漏收集', '泵区 GDS 连续监测', '高温法兰每班巡检'],
    linkedGds: 4,
    linkedVoc: 0,
    linkedMes: 6,
    linkedPlans: 2,
    dynamicFactors: [
      { source: 'GDS', label: 'GDS-101 浓度持续上升', impact: 'up', status: '38% LEL' },
      { source: '作业许可', label: '泵出口法兰一级动火', impact: 'up', status: '作业中' },
    ],
    assessments: [],
    controlRecords: [],
    version: 1,
    updatedAt: seededAt,
  },
  {
    id: 'risk-002',
    code: 'RU-TANK-201',
    name: 'T-201 汽油储罐单元',
    parentName: '成品油罐组',
    areaId: 'area-05',
    areaName: '储罐区',
    ownerDepartment: '储运部',
    owner: '何军',
    medium: '汽油',
    accidentTypes: ['火灾爆炸', '中毒窒息'],
    staticLevel: 'high',
    currentLevel: 'high',
    controls: ['液位高高联锁', '罐区泡沫灭火系统', '防火堤完整性月检'],
    linkedGds: 6,
    linkedVoc: 2,
    linkedMes: 4,
    linkedPlans: 2,
    dynamicFactors: [
      { source: 'VOC', label: '储罐呼吸气排口负荷偏高', impact: 'watch', status: '44 mg/m³' },
    ],
    assessments: [],
    controlRecords: [],
    version: 1,
    updatedAt: seededAt,
  },
];
